openapi: 3.0.0
info:
  title: JWT Authentication with Refresh Tokens
  version: 1.0.0

servers:
  - url: ${AUTHENTICATION_EXPRESS_ENDPOINT} 
    description: Development server

paths:
  /api/authentication/login:
    post:
      summary: Authenticate users with email and password
      description: Authenticate users with email and password and return the JWT and refresh token
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: "catalin@medical.equipment"
                password:
                  type: string
                  example: "MyOwnIsland1999"
              required:
                - email
                - password
      responses:
        "200":
          $ref: "#/components/responses/JWTRefreshTokenCookie"
        "400":
          description: Validation error
          content:
            application/json:
              schema:
                type: object
                properties:
                  type: 
                    type: string
                    example: "Validation error"
                  message:
                    type: object
                    properties:
                      email:
                        type: string
                        example: "Email is required"
                      password:
                        type: string
                        example: "Password is required"                
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/InvalidEmailOrPassword'
                  - $ref: '#/components/schemas/AccessRevoked'

  /api/authentication/logout:
    get:
      summary: Log out authenticated users
      description: Log out authenticated users by deleting the refreshToken cookie
      operationId: logout
      responses:
        "200":
          description: Logged out
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: "Logged out"
  
  /api/authentication/refresh-token:
    post:
      summary: Refresh JWT using a valid refresh token
      description: Refresh JWT using a valid refreshToken in a http only cookie
      operationId: refresh-token
      parameters:
        - in: cookie
          name: refreshToken
          required: true
          description: Refresh token can be sent in a cookie
          schema:
            type: string
            example: e1e43d4e-8351-4e96-8831-f1d3914e9066
      responses:
        "200":
          $ref: "#/components/responses/JWTRefreshTokenCookie"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Unauthorized"
                  - $ref: "#/components/schemas/AccessRevoked"
  
  /api/authentication/revoke-token:
    post:
      summary: Revoke a refresh token
      description: Revoke a refresh token as owner user or admin
      operationId: revoke-token
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token: 
                  type: string
                  format: uuid
                  example: "e1e43d4e-8351-4e96-8831-f1d3914e9066"
              required:
                - token
      responses:
        "200":
          description: Token revoked
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: "Token revoked"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/TokenAlreadyRevoked"
                  - $ref: "#/components/schemas/InvalidRefreshToken"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Unauthorized"

  /api/authentication/invite-signup:
    post:
      summary: Invite an user with a valid email account to sign up
      description: Invite an user with a valid email account to sign up for a new account 
      operationId: invite-signup
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email: 
                  type: string
                  format: email
                  example: "simona@medical.equipment"
                firstName:
                  type: string
                  example: "Simona"
              required:
                - email
                - firstName
      responses:
        "200":
          description: Invitation to signup sent
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: "Invitation to signup sent"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/InvalidEmailOrFirstName"
                  - $ref: "#/components/schemas/AccountExistsForEmail"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/InvalidToken"
                  - $ref: "#/components/schemas/Unauthorized"
                  - $ref: "#/components/schemas/AccessRevoked"
                    

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  
  responses:
    JWTRefreshTokenCookie:
      description: JWT token, JWT token expiration date, refresh token
      headers:
        Set-Cookie:
          description: "refreshToken"
          schema:
            type: string
            example: refreshToken=e1e43d4e-8351-4e96-8831-f1d3914e9066; Domain=127.0.0.1; Path=/; Expires=Tue, 11 Aug 2020 11:22:37 GMT; HttpOnly
      content:
        application/json:
          schema:
            type: object
            properties:
              jwtToken:
                type: string
                example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwczovL21lZGljYWwuZXF1aXBtZW50L2p3dC9jbGFpbXMiOnsieC1oYXN1cmEtYWxsb3dlZC1yb2xlcyI6WyJVc2VyIiwiQWRtaW4iXSwieC1oYXN1cmEtZGVmYXVsdC1yb2xlIjoiVXNlciIsIngtaGFzdXJhLXVzZXItaWQiOiIxIn0sImlhdCI6MTU5NDU1Mjk1OCwiZXhwIjoxNTk0NTUzODU4fQ.mEMgsbfXnVVd0dQc-Oo16SG78ZhWTTkqmLBAYwrQhY8
              jwtTokenExpiry:
                type: string
                example: 2020-07-12T11:37:38.070Z
              refreshToken:
                type: object
                properties:
                  token:
                    type: string
                    example: e1e43d4e-8351-4e96-8831-f1d3914e9066
                  expiresAt:
                    type: string
                    example: 2020-08-11T11:22:38.070Z
  
  schemas:
    InvalidToken:
      type: object
      properties:
        type: 
          type: string
          example: "Unauthorized"
        message:
          type: string
          example: "Invalid token"
    Unauthorized:
      type: object
      properties:
        type: 
          type: string
          example: "Unauthorized"
        message:
          type: string
          example: "Unauthorized"
    AccessRevoked:
      type: object
      properties:
        type: 
          type: string
          example: "Unauthorized"
        message:
          type: string
          example: "Access revoked"
    InvalidEmailOrPassword:
      type: object
      properties:
        type: 
          type: string
          example: "Unauthorized"
        message:
          type: string
          example: "Invalid email or password"
    InvalidEmailOrFirstName:
      type: object
      properties:
        type: 
          type: string
          example: "Validation error"
        message:
          type: object
          properties:
            email:
              type: string
              example: "Email is required"
            firstName:
              type: string
              example: "First name is required"
    AccountExistsForEmail:
      type: object
      properties:
        type: 
          type: string
          example: "Bad request"
        message:
          type: string
          example: "Account already exists for this email"
    TokenAlreadyRevoked:
      type: object
      properties:
        type: 
          type: string
          example: "Bad request"
        message:
          type: string
          example: "Token already revoked"
    InvalidRefreshToken:
      type: object
      properties:
        type: 
          type: string
          example: "Validation error"
        message:
          type: object
          properties:
            token:
              type: string
              example: "Token is not valid"
              