get:
  summary: Undo revoke user's access
  description: Undo revoke user's access as a logged in admin
  operationId: undo-revoke-access
  security:
    - bearerAuth: []
  parameters:
    - in: path
      name: userId
      description: User id
      required: true
      example: "91c4f2ba-81d7-4ac6-91f5-11a6c30da3d1"
      schema:
        type: string
  responses:
    "200":
      description: Access revoked undone
      content:
        application/json:
          schema:
            type: object
            properties:
              result:
                type: string
                example: "Access revoked undone"
    "400":
      description: Bad request
      content:
        application/json:
          schema:
            oneOf:
              - $ref: "#/components/schemas/NoAccountForId"
              - $ref: "#/components/schemas/InvalidUserId"
              - $ref: "#/components/schemas/AccessNotRevoked"
    "401":
      description: Unauthorized
      content:
        application/json:
          schema:
            oneOf:
              - $ref: "#/components/schemas/InvalidToken"
              - $ref: "#/components/schemas/Unauthorized"
              - $ref: "#/components/schemas/AccessRevoked"
              - $ref: "#/components/schemas/CannotUndoRevokeAccessOwnAccount"