post:
  summary: Authenticate users with email and password
  description: Authenticate users with email and password and return the JWT and refresh token
  operationId: login
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            email:
              type: string
              format: email
              example: "catalin@medical.equipment"
            password:
              type: string
              example: "MyOwnIsland1999"
          required:
            - email
            - password
  responses:
    "200":
      $ref: "#/components/responses/JWTRefreshTokenCookie"
    "400":
      description: Validation error
      content:
        application/json:
          schema:
            type: object
            properties:
              type: 
                type: string
                example: "Validation error"
              message:
                type: object
                properties:
                  email:
                    type: string
                    example: "Email is required"
                  password:
                    type: string
                    example: "Password is required"                
    "401":
      description: Unauthorized
      content:
        application/json:
          schema:
            oneOf:
              - $ref: '#/components/schemas/InvalidEmailOrPassword'
              - $ref: '#/components/schemas/AccessRevoked'